[build]
  command = "npm run build"
  publish = "client/.next"

[functions]
  external_node_modules = ["express", "serverless-http", "mongoose", "cors", "helmet", "morgan", "dotenv", "multer", "@supabase/supabase-js"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
